###########################
# Build da aplicação
###########################
FROM ubuntu:latest AS build

# Instalar Java 17 e Maven
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk maven && \
    apt-get clean

# Diretório de trabalho
WORKDIR /app

# Copiar todo o código
COPY . .

# Build do projeto
RUN mvn clean package -DskipTests

###########################
# Imagem final
###########################
FROM openjdk:17-jdk-slim

# Diretório de trabalho
WORKDIR /app

# Expor porta
EXPOSE 8080

# Copiar o JAR do build anterior
COPY --from=build /app/target/MpFitnessBack-0.0.1-SNAPSHOT.jar MpFitnessBack-0.0.1-SNAPSHOT.jar

# Comando de inicialização
ENTRYPOINT ["java", "-jar", "MpFitnessBack-0.0.1-SNAPSHOT.jar"]
